#! /usr/bin/env lua

-- Copyright (c) 2024,2026 <dev@brigid.jp>
-- This software is released under the MIT License.
-- https://opensource.org/licenses/mit-license.php

local csn7_version = "1.14"

----------------------------------------------------------------------

local brigid = require "brigid"
brigid.dlopen_self()

---@diagnostic disable-next-line: deprecated
local unpack = table.unpack or unpack

----------------------------------------------------------------------

-- 暗号学的に安全な乱数ではないが、問題ない用途である。
local handle = io.open("/dev/urandom", "rb")
if handle then
  local a, b, c, d = string.byte(handle:read(4), 1, 4)
  handle:close()
  math.randomseed(a * 0x1000000 + b * 0x1000000 + c * 0x100 + d)
else
  math.randomseed(os.time())
end

----------------------------------------------------------------------

local csn7_ua = "csn7/"..csn7_version.." brigid/"..brigid.get_version()

-- https://www.iana.org/assignments/media-types/media-types.xhtml
local media_types = {
  json = "application/json";
  urlencoded = "application/x-www-form-urlencoded";
  multipart = "multipart/form-data";
  octet_stream = "application/octet-stream";
  jpg = "image/jpeg";
  jpeg = "image/jpeg";
  png = "image/png";
  webp = "image/webp";
}

local bsky_url = "https://bsky.social/xrpc"
local slack_url = "https://slack.com/api"
local ai_novelist_url = "https://api.tringpt.com/api"

local boundary_table = {}

local a, b = ("09"):byte(1, 2)
for byte = a, b do
  boundary_table[#boundary_table + 1] = string.char(byte)
end

local a, b = ("AZ"):byte(1, 2)
for byte = a, b do
  boundary_table[#boundary_table + 1] = string.char(byte)
end

local a, b = ("az"):byte(1, 2)
for byte = a, b do
  boundary_table[#boundary_table + 1] = string.char(byte)
end

----------------------------------------------------------------------

local function read_contents(handle_or_path)
  local handle = handle_or_path
  if not handle.close then
    handle, message = io.open(handle_or_path, "rb")
    if not handle then
      return handle, message
    end
  end

  local contents = handle:read "*a"
  handle:close()
  return contents
end

local function read_json(handle_or_path)
  local result, message = read_contents(handle_or_path)
  if not result then
    return result, message
  end
  return brigid.json.parse(result)
end

local function read_lines(handle)
  local result = {}
  for line in handle:lines() do
    result[#result + 1] = line
  end
  return result
end

local function stringify_json(data)
  return tostring(brigid.data_writer():write_json(data, 2))
end

-- utf8.charpatternと互換な正規表現を使う。
-- [\x00-\x7F\xC2-\xF4][\x80-\xBF]*
-- コードポイントを数えているので結合文字の場合は正しくない値になる。
local function count_utf8(s)
  local s = tostring(s)
  local c = 0
  local n = 0
  for char in s:gmatch "[%z\1-\127\194-\244][\128-\191]*" do
    c = c + 1
    n = n + #char
  end
  assert(n == #s)
  if utf8 then
    assert(c == utf8.len(s))
  end
  return c
end

----------------------------------------------------------------------

local class = {}
local metatable = { __index = class }

function class.construct(config)
  local self = { config = config }
  self.http_session = brigid.http_session {
    header = function (code, header)
      self.response.code = code
      self.response.header = header
    end;
    write = function (out)
      self.response.data_writer:write(out)
    end;
  }
  return self
end

function class.new(config)
  return setmetatable(class.construct(config), metatable)
end

function class:debug(...)
  if self.config.debug then
    local debug_path = self.config.data_dirpath..os.date "/%Y-%m-%d.log"
    if self.debug_path ~= debug_path then
      self.debug_path = debug_path
      if self.debug_handle then
        self.debug_handle:close()
      end
      self.debug_handle = assert(io.open(debug_path, "ab"))
    end

    local out = self.debug_handle
    out:write(os.date "[%Y-%m-%d %H:%M:%S]" --[[@as string]])
    for _, v in ipairs {...} do
      out:write("\t", tostring(v))
    end
    out:write "\n"
  end
end

function class:warn(...)
  io.stderr:write(table.concat({...}, "\t"), "\n")
end

function class:make_header(source, content_type)
  local result = {
    ["User-Agent"] = self.config.ua or csn7_ua;
    ["Content-Type"] = content_type;
  }
  for k, v in pairs(source) do
    result[k] = v
  end
  return result
end

function class:request(method, url, header, data)
  self.response = { data_writer = brigid.data_writer() }

  if self.config.debug then
    self:debug "[request]"
    self:debug(method, url)
    self:debug(stringify_json(header))

    local content_type = header["Content-Type"]
    if content_type and not content_type:find "image/" and not content_type:find "multipart/form%-data" then
      self:debug(tostring(data))
    end
  end

  local result, message = self.http_session:request {
    method = method;
    url = url;
    header = header;
    data = data;
  }
  if not result then
    return result, message
  end

  if self.config.debug then
    self:debug "[response]"
    self:debug(self.response.code)
    self:debug(stringify_json(self.response.header))
    if #self.response.data_writer < 65536 then
      self:debug(tostring(self.response.data_writer))
    end
  end

  return self.response
end

function class:open_multipart()
  local boundary = {}
  for i = 1, 60 do
    boundary[i] = boundary_table[math.random(#boundary_table)]
  end

  return {
    boundary = "----"..table.concat(boundary);
    data_writer = brigid.data_writer();
  }
end

function class:add_part(that, name, value)
  that.data_writer
    :write "--"
    :write(that.boundary)
    :write "\r\n"
    :write "Content-Disposition: form-data; name=\""
    :write(name)
    :write "\""
    :write "\r\n"
    :write "\r\n"
    :write(value)
    :write "\r\n"
  return self
end

function class:add_part_file(that, name, path)
  local data, message = read_contents(path)
  if not data then
    return data, message
  end

  local filename = path:match "([^\\/]+)[\\/]*$"
  local suffix = path:match "%.([^.]+)$"
  local content_type = media_types[suffix]

  that.data_writer
    :write "--"
    :write(that.boundary)
    :write "\r\n"
    :write "Content-Disposition: form-data; name=\""
    :write(name)
    :write "\""
  if filename then
    that.data_writer
      :write "; filename=\""
      :write(filename)
      :write "\""
  end
  that.data_writer
    :write "\r\n"
  if content_type then
    that.data_writer
      :write "Content-Type: "
      :write(content_type)
      :write "\r\n"
  end
  that.data_writer
    :write "\r\n"
    :write(data)
    :write "\r\n"

  return self
end

function class:close_multipart(that)
  that.data_writer
    :write "--"
    :write(that.boundary)
    :write "--"
    :write "\r\n"
  return self
end

----------------------------------------------------------------------

function class:get_session_path(name)
  return self.config.data_dirpath.."/session-"..name..".json"
end

function class:save_session(name, data)
  local writer, message = brigid.file_writer(self:get_session_path(name))
  if not writer then
    return writer, message
  end
  return writer:write(data):close()
end

function class:load_session(name)
  local session, message = read_json(self:get_session_path(name))
  if not session then
    return session, message
  end
  self.session = session
  return session
end

----------------------------------------------------------------------

function class:post(endpoint, authz, content_type, data, refreshed)
  local authorization
  if authz == "access" then
    authorization = "Bearer "..self.session.accessJwt
  elseif authz == "refresh" then
    authorization = "Bearer "..self.session.refreshJwt
  end

  local url = bsky_url.."/"..endpoint
  local response, message = self:request("POST", url, self:make_header({
    Authorization = authorization;
  }, content_type), data)
  if not response then
    return response, message
  end

  local response_content_type = response.header["Content-Type"]
  if not response_content_type or not response_content_type:find(media_types.json, 1, true) then
    if response.code ~= 200 then
      return nil, response.code
    end
    return tostring(response.data_writer)
  end

  local result, message = brigid.json.parse(response.data_writer)
  if not result then
    return result, message
  end

  if not refreshed and response.code == 400 and result.error == "ExpiredToken" then
    self:warn("session expired: "..url)
    if authz == "access" then
      local session, message = self:refresh_session(self.session.name)
      if session then
        self:warn "session refreshed"
        return self:post(endpoint, authz, content_type, data, true)
      else
        self:warn("cannot refresh session: "..message)
      end
    elseif authz == "refresh" then
      local name = self.session.name
      local cred = self.config.bsky.credentials[name]
      if cred then
        local session, message = self:create_session(name, cred.identifier, cred.password)
        if session then
          self:warn "session recreated"
          return self:post(endpoint, authz, content_type, data, true)
        else
          self:warn("cannot recreate session: "..message)
        end
      else
        self:warn "cannot recreate session: cred not found"
      end
    end
  end

  if response.code ~= 200 then
    return nil, result.error..": "..result.message
  end
  return result
end

function class:get_impl(url, refreshed)
  local response, message = self:request("GET", url, self:make_header {
    Authorization = "Bearer "..self.session.accessJwt;
  })
  if not response then
    return response, message
  end

  local content_type = response.header["Content-Type"]
  if not content_type or not content_type:find(media_types.json, 1, true) then
    if response.code ~= 200 then
      return nil, response.code
    end
    return tostring(response.data_writer)
  end

  local result, message = brigid.json.parse(response.data_writer)
  if not result then
    return result, message
  end

  if not refreshed and response.code == 400 and result.error == "ExpiredToken" then
    self:warn("session expired: "..url)
    local session, message = self:refresh_session(self.session.name)
    if session then
      self:warn "session refreshed"
      return self:get_impl(url, true)
    else
      self:warn("cannot refresh session: "..message)
    end
  end

  if response.code ~= 200 then
    return nil, result.error..": "..result.message
  end
  return result
end

function class:get(endpoint, params)
  local data_writer = brigid.data_writer()
    :write(bsky_url)
    :write "/"
    :write(endpoint)
  if params then
    local first = true
    for k, v in pairs(params) do
      if first then
        first = false
        data_writer:write "?"
      else
        data_writer:write "&"
      end
      data_writer
        :write_urlencoded(k)
        :write "="
        :write_urlencoded(v)
    end
  end
  return self:get_impl(tostring(data_writer))
end

----------------------------------------------------------------------

function class:create_session(name, identifier, password)
  local session, message = self:post("com.atproto.server.createSession", nil, media_types.json, stringify_json {
    identifier = identifier;
    password = password;
  })
  if not session then
    return session, message
  end
  session.name = name
  self.session = session
  local result, message = self:save_session(name, stringify_json(session))
  if not result then
    return result, message
  end
  return session, message
end

function class:refresh_session(name)
  local session, message = self:post("com.atproto.server.refreshSession", "refresh")
  if not session then
    return session, message
  end
  session.name = name
  self.session = session
  local result, message = self:save_session(name, stringify_json(session))
  if not result then
    return result, message
  end
  return session, message
end

function class:delete_session(name)
  return self:post("com.atproto.server.deleteSession", "refresh")
end

----------------------------------------------------------------------

function class:get_record(repo, rkey)
  return self:get("com.atproto.repo.getRecord", {
    repo = repo;
    collection = "app.bsky.feed.post";
    rkey = rkey;
  })
end

function class:get_profile(actor)
  return self:get("app.bsky.actor.getProfile", { actor = actor })
end

function class:upload_blob(content_type, data)
  return self:post("com.atproto.repo.uploadBlob", "access", content_type, data)
end

----------------------------------------------------------------------

-- CommonMark
--   https://spec.commonmark.org/
-- GitHub Flavored Markdown
--   https://github.github.com/gfm/
-- Slack
--   https://api.slack.com/reference/surfaces/formatting

-- https://atproto.com/specs/handle
-- https://atproto.com/specs/record-key

function class:make_record(source)
  local reply
  local quote
  local images
  local buffer = {}

  for i, line in ipairs(source) do
    local processed
    local command, tail = line:match "^!([@>[])(.+)$"
    if i then
      if command == "[" then
        -- ![text](path)
        local text, path = tail:match "([^%]]*)%]%(([^)]+)%)$"
        if text then
          local suffix = path:match "%.([^.]+)$"
          local content_type = media_types[suffix]
          if content_type then
            local data, message = read_contents(path)
            if data then
              local image = {
                alt = text;
                image = {
                  path = path;
                  content_type = content_type;
                  data = data;
                  size = #data;
                };
              }
              if images then
                images[#images + 1] = image
              else
                images = { image }
              end
              processed = true
            else
              self:warn("cannot read_contents: "..message)
            end
          else
            self:warn("media type unknown: "..path)
          end
        end
      elseif command == "@" then
        -- !@repo/rkey
        local repo, rkey = tail:match "([0-9A-Za-z%-]+%.bsky%.social).*/([2-7a-z]+)$"
        if repo then
          local record, message = self:get_record(repo, rkey)
          if record then
            reply = {
              parent = {
                uri = record.uri;
                cid = record.cid;
              };
            }
            if record.value.reply then
              reply.root = record.value.reply.root
            else
              reply.root = reply.parent
            end
            processed = true
          else
            self:warn("cannot get_record: "..message)
          end
        end
      elseif command == ">" then
        -- !>repo/rkey
        local repo, rkey = tail:match "([0-9A-Za-z%-]+%.bsky%.social).*/([2-7a-z]+)$"
        if repo then
          local record, message = self:get_record(repo, rkey)
          if record then
            quote = {
              uri = record.uri;
              cid = record.cid;
            }
            processed = true
          else
            self:warn("cannot get_record: "..message)
          end
        end
      end
    end

    if not processed then
      local p = 1
      while true do
        local i, j, text, command = line:find("^(.-)([[<@#])", p)
        if not i then
          break
        end
        if text ~= "" then
          buffer[#buffer + 1] = { text = text }
        end
        p = j + 1

        if command == "[" then
          -- [text](link)
          local i, j, text, link = line:find("^(.-)%]%((.-)%)", p)
          if i then
            if text == "" then
              text = link
            end
            buffer[#buffer + 1] = {
              text = text;
              feature = {
                ["$type"] = "app.bsky.richtext.facet#link";
                uri = link;
              };
            }
            p = j + 1
          else
            buffer[#buffer + 1] = { text = "[" }
          end
        elseif command == "<" then
          -- <link>
          local i, j, link = line:find("^(.-)>", p)
          if i then
            buffer[#buffer + 1] = {
              text = link;
              feature = {
                ["$type"] = "app.bsky.richtext.facet#link";
                uri = link;
              };
            }
            p = j + 1
          else
            buffer[#buffer + 1] = { text = "<" }
          end
        elseif command == "@" then
          -- @mention
          local i, j, mention = line:find("^([^[<@#%s]+)", p)
          if i then
            local profile, message = self:get_profile(mention)
            if profile then
              buffer[#buffer + 1] = {
                text = "@"..mention;
                feature = {
                  ["$type"] = "app.bsky.richtext.facet#mention";
                  did = profile.did;
                };
              }
            else
              self:warn("cannot get_profile: "..message)
              buffer[#buffer + 1] = { text = "@"..mention }
            end

            p = j + 1
          else
            buffer[#buffer + 1] = { text = "@" }
          end
        elseif command == "#" then
          -- #tag （数字だけの場合は不許可）
          local i, j, tag = line:find("^([^[<@#%s]+)", p)
          if i and not tag:find "^%d+$" then
            buffer[#buffer + 1] = {
              text = "#"..tag;
              feature = {
                ["$type"] = "app.bsky.richtext.facet#tag";
                tag = tag;
              };
            }
            p = j + 1
          else
            buffer[#buffer + 1] = { text = "#" }
          end
        end
      end

      if p <= #line then
        buffer[#buffer + 1] = { text = line:sub(p) }
      end
      buffer[#buffer + 1] = { text = "\n" }
    end
  end

  for i = #buffer, 1, -1 do
    local v = buffer[i]
    if not v.feature and v.text:find "^%s*$" then
      buffer[i] = nil
    else
      break
    end
  end

  local data_writer = brigid.data_writer()
  local facets
  local trim = true
  for _, v in ipairs(buffer) do
    if v.feature then
      local n = #data_writer
      local facet = {
        index = {
          byteStart = n;
          byteEnd = n + #v.text;
        };
        features = { v.feature };
      }
      if facets then
        facets[#facets + 1] = facet
      else
        facets = { facet }
      end
      data_writer:write(v.text)
      trim = false
    else
      if not trim or not v.text:find "^%s*$" then
        data_writer:write(v.text)
        trim = false
      end
    end
  end

  local record = {
    ["$type"] = "app.bsky.feed.post";
    text = data_writer;
    createdAt = os.date "!%Y-%m-%dT%H:%M:%SZ";
    langs = self.config.bsky.langs;
    facets = facets;
    reply = reply;
  }

  self:set_quote(record, quote)
  self:set_images(record, images)

  return record, images
end

function class:set_reply(record, reply)
  record.reply = reply
end

function class:set_quote(record, quote)
  local embed = record.embed
  if quote then
    if embed then
      if embed["$type"] == "app.bsky.embed.images" then
        record.embed = {
          ["$type"] = "app.bsky.embed.recordWithMedia";
          record = {
            ["$type"] = "app.bsky.embed.record";
            record = quote;
          };
          media = embed;
        }
      elseif embed["$type"] == "app.bsky.embed.record" then
        embed.record = quote
      elseif embed["$type"] == "app.bsky.embed.recordWithMedia" then
        embed.record.record = quote
      end
    else
      record.embed = {
        ["$type"] = "app.bsky.embed.record";
        record = quote;
      }
    end
  elseif embed then
    if embed["$type"] == "app.bsky.embed.record" then
      record.embed = nil
    elseif embed["$type"] == "app.bsky.embed.recordWithMedia" then
      record.embed = {
        ["$type"] = "app.bsky.embed.images";
        images = embed.images;
      }
    end
  end
end

function class:set_images(record, images)
  local embed = record.embed
  if images then
    if embed then
      if embed["$type"] == "app.bsky.embed.images" then
        embed.images = images
      elseif embed["$type"] == "app.bsky.embed.record" then
        record.embed = {
          ["$type"] = "app.bsky.embed.recordWithMedia";
          record = embed;
          media = {
            ["$type"] = "app.bsky.embed.images";
            images = images;
          };
        }
      elseif embed["$type"] == "app.bsky.embed.recordWithMedia" then
        embed.media.images = images
      end
    else
      record.embed = {
        ["$type"] = "app.bsky.embed.images";
        images = images;
      }
    end
  elseif embed then
    if embed["$type"] == "app.bsky.embed.images" then
      record.embed = nil
    elseif embed["$type"] == "app.bsky.embed.recordWithMedia" then
      record.embed = {
        ["$type"] = "app.bsky.embed.record";
        record = embed.record;
      }
    end
  end
end

----------------------------------------------------------------------

local commands = {}

function commands:create_session(name)
  local cred = assert(self.config.bsky.credentials[name])
  assert(self:create_session(name, cred.identifier, cred.password))
end

function commands:refresh_session(name)
  assert(self:load_session(name))
  assert(self:refresh_session(name))
end

function commands:delete_session(name)
  assert(self:load_session(name))
  assert(self:delete_session(name))
end

----------------------------------------------------------------------

function commands:get_record(name, rkey, repo)
  assert(self:load_session(name))
  if not repo then
    repo = self.config.bsky.credentials[name].identifier
  end
  local r = assert(self:get_record(repo, rkey))
  io.write(stringify_json(r), "\n")
end

function commands:get_profile(name, actor)
  assert(self:load_session(name))
  if not actor then
    actor = self.config.bsky.credentials[name].identifier
  end
  local r = assert(self:get_profile(actor))
  io.write(stringify_json(r), "\n")
end

function commands:get_followers(name, actor)
  assert(self:load_session(name))
  if not actor then
    actor = self.config.bsky.credentials[name].identifier
  end

  local r = {}
  local followers = brigid.json.array()

  repeat
    r = assert(self:get("app.bsky.graph.getFollowers", {
      actor = actor;
      cursor = r.cursor;
    }))

    for _, follower in ipairs(r.followers) do
      followers[#followers + 1] = follower
    end
  until not r.cursor

  r.followers = followers
  io.write(stringify_json(r), "\n")
end

function commands:get_follows(name, actor)
  assert(self:load_session(name))
  if not actor then
    actor = self.config.bsky.credentials[name].identifier
  end

  local r = {}
  local follows = brigid.json.array()

  repeat
    r = assert(self:get("app.bsky.graph.getFollows", {
      actor = actor;
      cursor = r.cursor;
    }))

    for _, follow in ipairs(r.follows) do
      follows[#follows + 1] = follow
    end
  until not r.cursor

  r.follows = follows
  io.write(stringify_json(r), "\n")
end

----------------------------------------------------------------------

function commands:make_record(name)
  assert(self:load_session(name))
  local lines = read_lines(io.stdin)
  local r, images = assert(self:make_record(lines))
  local char_count = count_utf8(r.text)
  local image_size = 0
  if images then
    for _, v in ipairs(images) do
      v.image.data = nil
      image_size = image_size + v.image.size
    end
  end

  io.write(stringify_json(r), "\n")
  io.stderr:write(tostring(r.text), "\n")
  io.stderr:write(("-"):rep(60), "\n")
  io.stderr:write(("文字数:    %8d (%s)\n"):format(char_count, char_count <= 300 and "OK" or "NG"))
  io.stderr:write(("画像サイズ:%8d (%s)\n"):format(image_size, image_size <= 1000000 and "OK" or "NG"))
end

function commands:create_record(name)
  local session = assert(self:load_session(name))
  local lines = read_lines(io.stdin)
  local record, images = assert(self:make_record(lines))

  if images then
    for _, v in ipairs(images) do
      local blob = assert(self:upload_blob(v.image.content_type, v.image.data))
      v.image = blob.blob
    end
  end

  local r = assert(self:post("com.atproto.repo.createRecord", "access", media_types.json, stringify_json {
    repo = self.config.bsky.credentials[name].identifier;
    collection = "app.bsky.feed.post";
    record = record;
  }))
  io.write(stringify_json(r), "\n")
end

----------------------------------------------------------------------

function commands:slack(name, channel, username, iconname)
  local app = assert(self.config.slack.apps[name])
  local text = io.read "*a"

  if username then
    local a, groupname, b = username:match "^(.-)%%random:([^%%]*)%%(.*)$"
    if a then
      local group = assert(self.config.slack.groups[groupname])
      local avator = group[math.random(#group)]
      username = a..avator.username..b
      iconname = avator.iconname
    end
  end

  assert(self:request("POST", slack_url.."/chat.postMessage", self:make_header({
    Authorization = "Bearer "..app.oauth_token;
  }, media_types.json), stringify_json {
    token = app.oauth_token;
    channel = assert(channel);
    blocks = {
      {
        type = "section";
        text = {
          type = "mrkdwn";
          text = text;
        };
      };
    };
    username = username;
    icon_url = self.config.icons[iconname];
  }))
end

function commands:slack_upload(name, channel, path, initial_comment)
  local app = assert(self.config.slack.apps[name])

  local multipart = self:open_multipart()
  assert(self:add_part(multipart, "channels", channel))
  assert(self:add_part_file(multipart, "file", path))
  if initial_comment then
    assert(self:add_part(multipart, "initial_comment", initial_comment))
  end
  assert(self:close_multipart(multipart))

  local response = assert(self:request("POST", slack_url.."/files.upload", self:make_header({
    Authorization = "Bearer "..app.oauth_token;
  }, media_types.multipart.."; boundary="..multipart.boundary), multipart.data_writer))

  local r = assert(brigid.json.parse(response.data_writer))
  io.write(stringify_json(r), "\n")
end

function commands:slack_upload_v2(name, channel_id, path, initial_comment)
  local app = assert(self.config.slack.apps[name])

  local contents = assert(read_contents(path))

  local filename = assert(path:match "([^\\/]+)[\\/]*$")
  local suffix = path:match "%.([^.]+)$"
  local content_type = media_types[suffix]
  if not content_type then
    content_type = media_types.octet_stream
  end

  local data_writer = brigid.data_writer()
    :write_urlencoded "filename"
    :write "="
    :write_urlencoded(filename)
    :write "&"
    :write_urlencoded "length"
    :write "="
    :write_urlencoded(#contents)

  local response = assert(self:request("POST", slack_url.."/files.getUploadURLExternal", self:make_header({
    Authorization = "Bearer "..app.oauth_token;
  }, media_types.urlencoded), tostring(data_writer)))

  local r = assert(brigid.json.parse(response.data_writer))
  io.write(stringify_json(r), "\n")

  assert(response.code == 200)

  local response = assert(self:request("POST", assert(r.upload_url), self:make_header({
    Authorization = "Bearer "..app.oauth_token;
  }, content_type), contents))

  -- 応答はtext/plainだった。
  assert(response.code == 200)

  local response = assert(self:request("POST", slack_url.."/files.completeUploadExternal", self:make_header({
    Authorization = "Bearer "..app.oauth_token;
  }, media_types.json), stringify_json {
    files = { { id = assert(r.file_id) } };
    channel_id = channel_id;
    initial_comment = initial_comment;
  }))

  local r = assert(brigid.json.parse(response.data_writer))
  io.write(stringify_json(r), "\n")

  assert(response.code == 200)
end

----------------------------------------------------------------------

local driver_class = setmetatable({}, { __index = class })
local driver_metatable = { __index = driver_class }
local driver_commands = {}

function driver_class.new(config)
  return setmetatable(driver_class.construct(config), driver_metatable)
end

function driver_class:request(method, path, data)
  local url = self.config.driver.url..path
  local ignore_timeout = self.config.driver.ignore_timeout

  local content_type
  local content
  if data then
    content_type = media_types.json
    content = stringify_json(data)
  end
  local response, message = class.request(self, method, url, self:make_header({}, content_type), content)
  if not response then
    return response, message
  end

  local content_type = response.header["Content-Type"]
  if not content_type or not content_type:find(media_types.json, 1, true) then
    if response.code ~= 200 then
      return nil, response.code
    end
    return tostring(response.data_writer)
  end

  local result, message = brigid.json.parse(response.data_writer)
  if not result then
    return result, message
  end

  if self.config.driver.ignore_timeout and response.code == 500 and result.value.error == "timeout" then
    -- ChromeDriverがタイムアウトした場合にエラーとしない。
    self:debug "ignore_timeout"
    return result
  elseif response.code ~= 200 then
    return nil, result.value.error..": "..result.value.message
  end

  return result
end

function driver_class:get_session_path(name)
  return self.config.data_dirpath.."/driver_session-"..name..".json"
end

function driver_class:get_session_id(name)
  local session, message = read_json(self:get_session_path(name))
  if not session then
    return session, message
  end
  return session.sessionId
end

function driver_class:get_location_strategy(using)
  -- https://w3c.github.io/webdriver/#locator-strategies
  local location_strategies = {
    c = "css selector";
    l = "link text";
    p = "partial link text";
    t = "tag name";
    x = "xpath";
  }
  return location_strategies[using:sub(1, 1)]
end

function driver_class:find_element(session_id, using, value)
  if using:find "^e" then
    return value
  end
  local r, message = self:request("POST", "/session/"..session_id.."/element", {
    using = self:get_location_strategy(using);
    value = value;
  })
  if not r then
    return r, message
  end
  return select(2, next(r.value))
end

function driver_class:find_elements(session_id, using, value)
  if using:find "^e" then
    return { value }
  end
  local r, message = self:request("POST", "/session/"..session_id.."/elements", {
    using = self:get_location_strategy(using);
    value = value;
  })
  if not r then
    return r, message
  end
  local result = {}
  for i, v in ipairs(r.value) do
    result[i] = select(2, next(v))
  end
  return result
end

function driver_class:get_element_id(t)
  local _, v = next(t)
  return v
end

----------------------------------------------------------------------

function driver_commands:new_session(name, chrome_options_key)
  local session_id = self:get_session_id(name)
  if session_id then
    error("session exists: "..name)
  end

  local chrome_options
  if chrome_options_key then
    chrome_options = self.config.driver.chrome_options_map[chrome_options_key]
  else
    chrome_options = self.config.driver.chrome_options
  end

  local r = assert(self:request("POST", "/session", {
    capabilities = {
      alwaysMatch = {
        ["goog:chromeOptions"] = chrome_options;
      };
    };
  }))
  io.write(stringify_json(r), "\n")

  local handle = assert(io.open(self:get_session_path(name), "wb"))
  handle:write(stringify_json(r.value), "\n")
  handle:close()
end

function driver_commands:delete_session(name)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("DELETE", "/session/"..session_id))
  io.write(stringify_json(r), "\n")
  os.remove(self:get_session_path(name))
end

function driver_commands:status()
  local r = assert(self:request("GET", "/status"))
  io.write(stringify_json(r), "\n")
end

function driver_commands:set_url(name, url)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("POST", "/session/"..session_id.."/url", {
    url = url;
  }))
  io.write(stringify_json(r), "\n")
end

function driver_commands:get_url(name)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("GET", "/session/"..session_id.."/url"))
  io.write(r.value, "\n")
end

function driver_commands:back(name)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("POST", "/session/"..session_id.."/back", {}))
  io.write(stringify_json(r), "\n")
end

function driver_commands:forward(name)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("POST", "/session/"..session_id.."/forward", {}))
  io.write(stringify_json(r), "\n")
end

function driver_commands:refresh(name)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("POST", "/session/"..session_id.."/refresh", {}))
  io.write(stringify_json(r), "\n")
end

function driver_commands:find_element(name, using, value)
  local session_id = assert(self:get_session_id(name))
  local element_id = assert(self:find_element(session_id, using, value))
  io.write(element_id, "\n")
end

function driver_commands:find_elements(name, using, value)
  local session_id = assert(self:get_session_id(name))
  local element_ids = assert(self:find_elements(session_id, using, value))
  for _, v in ipairs(element_ids) do
    io.write(v, "\n")
  end
end

function driver_commands:get_attribute(name, using, value, attrname)
  local session_id = assert(self:get_session_id(name))
  local element_id = assert(self:find_element(session_id, using, value))
  local r = assert(self:request("GET", "/session/"..session_id.."/element/"..element_id.."/attribute/"..attrname))
  io.write(r.value, "\n")
end

function driver_commands:get_property(name, using, value, propname)
  local session_id = assert(self:get_session_id(name))
  local element_id = assert(self:find_element(session_id, using, value))
  local r = assert(self:request("GET", "/session/"..session_id.."/element/"..element_id.."/property/"..propname))
  io.write(r.value, "\n")
end

function driver_commands:get_text(name, using, value)
  local session_id = assert(self:get_session_id(name))
  local element_id = assert(self:find_element(session_id, using, value))
  local r = assert(self:request("GET", "/session/"..session_id.."/element/"..element_id.."/text"))
  io.write(r.value, "\n")
end

function driver_commands:click(name, using, value)
  local session_id = assert(self:get_session_id(name))
  local element_id = assert(self:find_element(session_id, using, value))
  local r = assert(self:request("POST", "/session/"..session_id.."/element/"..element_id.."/click", {}))
  io.write(stringify_json(r), "\n")
end

function driver_commands:set_value(name, using, value, text)
  local session_id = assert(self:get_session_id(name))
  local element_id = assert(self:find_element(session_id, using, value))
  local r = assert(self:request("POST", "/session/"..session_id.."/element/"..element_id.."/value", {
    text = text;
  }))
  io.write(stringify_json(r), "\n")
end

function driver_commands:source(name)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("GET", "/session/"..session_id.."/source"))
  io.write(r.value, "\n")
end

function driver_commands:execute(name, script, arg, ...)
  local session_id = assert(self:get_session_id(name))
  if not script then
    script = read_contents(io.stdin)
  end
  local args = arg and { arg, ... } or brigid.json.array()
  local r = assert(self:request("POST", "/session/"..session_id.."/execute/sync", {
    script = script;
    args = args;
  }))
  io.write(stringify_json(r), "\n")
end

function driver_commands:screenshot(name, using, value)
  local session_id = assert(self:get_session_id(name))
  if using and value then
    local element_id = assert(self:find_element(session_id, using, value))
    local r = assert(self:request("GET", "/session/"..session_id.."/element/"..element_id.."/screenshot"))
    io.write(r.value, "\n")
  else
    local r = assert(self:request("GET", "/session/"..session_id.."/screenshot"))
    io.write(r.value, "\n")
  end
end

function driver_commands:get_cookie(name, key)
  local session_id = assert(self:get_session_id(name))
  if key then
    local data_writer = brigid.data_writer()
      :write "/session/"
      :write(session_id)
      :write "/cookie/"
      :write_urlencoded(key)
    local r = assert(self:request("GET", tostring(data_writer)))
    io.write(stringify_json(r.value), "\n")
  else
    local r = assert(self:request("GET", "/session/"..session_id.."/cookie"))
    io.write(stringify_json(r.value), "\n")
  end
end

function driver_commands:add_cookie(name, key, value)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("POST", "/session/"..session_id.."/cookie", {
    cookie = {
      name = key;
      value = value;
    }
  }))
  io.write(stringify_json(r), "\n")
end

function driver_commands:get_timeouts(name)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("GET", "/session/"..session_id.."/timeouts"))
  io.write(stringify_json(r.value), "\n")
end

function driver_commands:set_timeouts(name, script, page_load, implicit)
  local session_id = assert(self:get_session_id(name))
  local r = assert(self:request("POST", "/session/"..session_id.."/timeouts", {
    script = tonumber(script);
    pageLoad = tonumber(page_load);
    implicit = tonumber(implicit);
  }))
  io.write(stringify_json(r), "\n")
end

----------------------------------------------------------------------

commands["ai-novelist"] = function (self, name, length, model)
  local text = io.read "*a"
  if not model then
    model = "supertrin_highpres"
  end
  if not length then
    length = 95
  end
  if not name then
    name = "novels"
  end

  local request = {
    text = text;
    length = length;
    model = model;
  }
  for k, v in pairs(assert(self.config["ai-novelist"].options[name])) do
    request[k] = v
  end

  local response = assert(self:request("POST", ai_novelist_url, self:make_header({
    Authorization = "Bearer "..self.config["ai-novelist"].auth_key;
  }, media_types.json), stringify_json(request)))

  local r = assert(brigid.json.parse(response.data_writer))
  io.write(text, table.concat(r.data), "\n")
end

----------------------------------------------------------------------

function commands:sleep(sec)
  brigid.sleep(sec * 1000000000)
end

function commands:info()
  io.write(stringify_json {
    program = arg[0];
    version = csn7_version;
    user_agent = csn7_ua;
  }, "\n")
end

function commands:help()
  io.write [=[
# Bluesky

csn7 create_session name
csn7 refresh_session name
csn7 delete_session name

csn7 get_record name rkey [repo]
csn7 get_profile name [actor]
csn7 get_followers name [actor]
csn7 get_follows name [actor]

cat post.txt | csn7 make_record name
cat post.txt | csn7 create_record name

# Slack

cat post.txt | csn7 slack name channel [username [iconname]]
csn7 slack_upload name channel path [initial_comment]
csn7 slack_upload_v2 name channel_id path [initial_comment]

# WebDriver

csn7 d:new_session name [chrome_options_key]
csn7 d:delete_session name
csn7 d:status

csn7 d:set_url name url
csn7 d:get_url name
csn7 d:back name
csn7 d:forward name
csn7 d:refresh name

csn7 d:find_element name using value
csn7 d:find_elements name using value
csn7 d:get_attribute name using value attrname
csn7 d:get_property name using value propname
csn7 d:get_text name using value

csn7 d:click name using value
csn7 d:set_value name using value text
csn7 d:source name

csn7 d:execute name script [...]
cat script.js | csn7 d:execute name
csn7 d:screenshot name
csn7 d:screenshot name using value

csn7 d:get_cookie name key
csn7 d:add_cookie name key value

csn7 d:get_timeouts name
csn7 d:set_timeouts name script page_load implicit

# Utilities

csn7 sleep sec
csn7 info
csn7 help
]=]
  os.exit(1)
end

----------------------------------------------------------------------

local home = os.getenv "HOME"
if not home then
  -- Windowsの場合
  home = assert(os.getenv "HOMEDRIVE")..assert(os.getenv "HOMEPATH")
end

local config_path = os.getenv "CONFIG_PATH"
if not config_path or config_path == "" then
  config_path = home.."/.csn7rc"
end
print(config_path)

local config = read_json(config_path) or {}

if not config.data_dirpath then
  config.data_dirpath = home.."/.csn7"
end
brigid.mkdir(config.data_dirpath)

local command = arg[1] or ""
local command_fn = commands[command]
local command_self = class.new(config)

if not command_fn then
  command_fn = driver_commands[command:gsub("^d[^:]*:", "")]
  if command_fn then
    command_self = driver_class.new(config)
  else
    command_self = nil
  end
end

if not command_fn then
  command_fn = commands.help
end
command_fn(command_self, unpack(arg, 2))
